# Generated by Django 3.2.12 on 2023-10-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('picture', models.FileField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='show_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('poster', models.FileField(upload_to='')),
                ('genre', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('story', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.category_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.register_tb')),
            ],
        ),
    ]
