# Generated by Django 3.2.12 on 2023-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist_tb',
            name='poster',
        ),
        migrations.AddField(
            model_name='watchlist_tb',
            name='rating',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
